version: "3.9"

networks:
  my-bridge:
    external: true

services:
  grpc-db:
    image: "postgres:14.5-alpine"
    container_name: grpc-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - my-bridge

  grpc-api:
    build: "./"
    container_name: grpc-api
    environment:
      - DB_HOST=grpc-db
      - DB_USER=postgres
      - DB_PASS=postgres      
      - DB_NAME=postgres
    ports:
      - "8000:8000"
    networks:
      - my-bridge
    depends_on:
      - grpc-db
    restart: on-failure

volumes:
  grpc-data:
